# Generated by Django 3.2.10 on 2021-12-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentusage',
            name='power_used',
        ),
        migrations.AddField(
            model_name='currentusage',
            name='total_power_used',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
